debug: false

logging:
    level:
      root: INFO
      org.springframework.web: INFO
      org.hibernate: INFO

server:
  port: 8080

spring:

  liquibase:
    clear-checksums: true
    change-log: db/changelog.xml

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/snippets?createDatabaseIfNotExist=true
